services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - /app/node_modules
    env_file:
      - ../.env
    command: yarn dev
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - scopely
    profiles: ["dev"]

  redis:
    image: redis:7
    ports:
      - "6399:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - scopely
    profiles: ["dev"]

networks:
  scopely:
    driver: bridge
